version: 2

models:
  - name: cons_customer_profile
    description: This table has basic information about a customer, as well as some derived facts based on a customer's orders

    columns:
      - name: customer_key
        description: This is a unique identifier for a customer
        tests:
          - unique
          - not_null